var a = global;
console.log(a);

// { console: [Getter],
//   DTRACE_NET_SERVER_CONNECTION: [Function],
//   DTRACE_NET_STREAM_END: [Function],
//   DTRACE_HTTP_SERVER_REQUEST: [Function],
//   DTRACE_HTTP_SERVER_RESPONSE: [Function],
//   DTRACE_HTTP_CLIENT_REQUEST: [Function],
//   DTRACE_HTTP_CLIENT_RESPONSE: [Function],
//   global: [Circular],
//   process: 
//    process {
//      title: 'node',
//      version: 'v8.11.3',
//      moduleLoadList: 
//       [ 'Binding contextify',
//         'Binding natives',
//         'Binding config',
//         'NativeModule events',
//         'Binding async_wrap',
//         'Binding icu',
//         'NativeModule util',
//         'NativeModule internal/errors',
//         'NativeModule internal/encoding',
//         'NativeModule internal/util',
//         'Binding util',
//         'Binding constants',
//         'NativeModule internal/util/types',
//         'Binding buffer',
//         'NativeModule buffer',
//         'NativeModule internal/buffer',
//         'Binding uv',
//         'NativeModule internal/process',
//         'NativeModule internal/process/warning',
//         'NativeModule internal/process/next_tick',
//         'NativeModule internal/async_hooks',
//         'NativeModule internal/process/promises',
//         'NativeModule internal/process/stdio',
//         'Binding performance',
//         'NativeModule perf_hooks',
//         'NativeModule internal/linkedlist',
//         'NativeModule internal/trace_events_async_hooks',
//         'Binding trace_events',
//         'NativeModule async_hooks',
//         'NativeModule internal/inspector_async_hook',
//         'Binding inspector',
//         'NativeModule timers',
//         'Binding timer_wrap',
//         'NativeModule assert',
//         'NativeModule module',
//         'NativeModule internal/module',
//         'NativeModule internal/url',
//         'NativeModule internal/querystring',
//         'NativeModule querystring',
//         'Binding url',
//         'NativeModule vm',
//         'NativeModule fs',
//         'NativeModule path',
//         'Binding fs',
//         'NativeModule stream',
//         'NativeModule internal/streams/legacy',
//         'NativeModule _stream_readable',
//         'NativeModule internal/streams/BufferList',
//         'NativeModule internal/streams/destroy',
//         'NativeModule _stream_writable',
//         'NativeModule _stream_duplex',
//         'NativeModule _stream_transform',
//         'NativeModule _stream_passthrough',
//         'Binding fs_event_wrap',
//         'NativeModule internal/fs',
//         'NativeModule internal/loader/Loader',
//         'NativeModule internal/loader/ModuleWrap',
//         'Internal Binding module_wrap',
//         'NativeModule internal/loader/ModuleMap',
//         'NativeModule internal/loader/ModuleJob',
//         'NativeModule internal/safe_globals',
//         'NativeModule internal/loader/ModuleRequest',
//         'NativeModule url',
//         'NativeModule internal/loader/search',
//         'NativeModule console',
//         'Binding tty_wrap',
//         'NativeModule tty',
//         'NativeModule net',
//         'NativeModule internal/net',
//         'Binding cares_wrap',
//         'Binding tcp_wrap',
//         'Binding pipe_wrap',
//         'Binding stream_wrap',
//         'NativeModule dns',
//         'NativeModule readline',
//         'NativeModule string_decoder',
//         'NativeModule internal/readline',
//         'Binding signal_wrap' ],
//      versions: 
//       { http_parser: '2.8.0',
//         node: '8.11.3',
//         v8: '6.2.414.54',
//         uv: '1.19.1',
//         zlib: '1.2.11',
//         ares: '1.10.1-DEV',
//         modules: '57',
//         nghttp2: '1.32.0',
//         napi: '3',
//         openssl: '1.0.2o',
//         icu: '60.1',
//         unicode: '10.0',
//         cldr: '32.0',
//         tz: '2017c' },
//      arch: 'x64',
//      platform: 'darwin',
//      release: 
//       { name: 'node',
//         lts: 'Carbon',
//         sourceUrl: 'https://nodejs.org/download/release/v8.11.3/node-v8.11.3.tar.gz',
//         headersUrl: 'https://nodejs.org/download/release/v8.11.3/node-v8.11.3-headers.tar.gz' },
//      argv: 
//       [ '/Users/a408113/.nvm/versions/node/v8.11.3/bin/node',
//         '/Users/a408113/Development/JS/js_study/isTrustedTest.js' ],
//      execArgv: [],
//      env: 
//       { TERM_PROGRAM: 'Apple_Terminal',
//         NVM_CD_FLAGS: '',
//         SHELL: '/bin/bash',
//         TERM: 'xterm-256color',
//         TMPDIR: '/var/folders/bc/5y4glm1507n7np4bflq7g4_00000gn/T/',
//         Apple_PubSub_Socket_Render: '/private/tmp/com.apple.launchd.lFqUi9Q9De/Render',
//         TERM_PROGRAM_VERSION: '404',
//         TERM_SESSION_ID: '5FD5DFEC-B2C5-4D49-8114-AD016CA8A2B6',
//         NVM_DIR: '/Users/a408113/.nvm',
//         USER: 'a408113',
//         SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.cVeXHUW7uw/Listeners',
//         PATH: '/Users/a408113/.nvm/versions/node/v8.11.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin',
//         PWD: '/Users/a408113/Development/JS/js_study',
//         LANG: 'ko_KR.UTF-8',
//         XPC_FLAGS: '0x0',
//         XPC_SERVICE_NAME: '0',
//         SHLVL: '1',
//         HOME: '/Users/a408113',
//         LOGNAME: 'a408113',
//         NVM_BIN: '/Users/a408113/.nvm/versions/node/v8.11.3/bin',
//         DISPLAY: '/private/tmp/com.apple.launchd.PaZH8ydwlH/org.macosforge.xquartz:0',
//         _: '/Users/a408113/.nvm/versions/node/v8.11.3/bin/node',
//         OLDPWD: '/Users/a408113/Development/JS',
//         __CF_USER_TEXT_ENCODING: '0x1F5:0x3:0x33' },
//      pid: 43032,
//      features: 
//       { debug: false,
//         uv: true,
//         ipv6: true,
//         tls_npn: true,
//         tls_alpn: true,
//         tls_sni: true,
//         tls_ocsp: true,
//         tls: true },
//      ppid: 41797,
//      execPath: '/Users/a408113/.nvm/versions/node/v8.11.3/bin/node',
//      debugPort: 9229,
//      _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
//      _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
//      _getActiveRequests: [Function: _getActiveRequests],
//      _getActiveHandles: [Function: _getActiveHandles],
//      reallyExit: [Function: reallyExit],
//      abort: [Function: abort],
//      chdir: [Function: chdir],
//      cwd: [Function: cwd],
//      umask: [Function: umask],
//      getuid: [Function: getuid],
//      geteuid: [Function: geteuid],
//      setuid: [Function: setuid],
//      seteuid: [Function: seteuid],
//      setgid: [Function: setgid],
//      setegid: [Function: setegid],
//      getgid: [Function: getgid],
//      getegid: [Function: getegid],
//      getgroups: [Function: getgroups],
//      setgroups: [Function: setgroups],
//      initgroups: [Function: initgroups],
//      _kill: [Function: _kill],
//      _debugProcess: [Function: _debugProcess],
//      _debugPause: [Function: _debugPause],
//      _debugEnd: [Function: _debugEnd],
//      hrtime: [Function: hrtime],
//      cpuUsage: [Function: cpuUsage],
//      dlopen: [Function: dlopen],
//      uptime: [Function: uptime],
//      memoryUsage: [Function: memoryUsage],
//      binding: [Function: binding],
//      _linkedBinding: [Function: _linkedBinding],
//      _setupDomainUse: [Function: _setupDomainUse],
//      _events: 
//       { newListener: [Function],
//         removeListener: [Function],
//         warning: [Function],
//         SIGWINCH: [Array] },
//      _rawDebug: [Function],
//      _eventsCount: 4,
//      domain: null,
//      _maxListeners: undefined,
//      _fatalException: [Function],
//      _exiting: false,
//      assert: [Function],
//      config: { target_defaults: [Object], variables: [Object] },
//      emitWarning: [Function],
//      nextTick: [Function: nextTick],
//      _tickCallback: [Function: _tickCallback],
//      _tickDomainCallback: [Function: _tickDomainCallback],
//      stdout: [Getter],
//      stderr: [Getter],
//      stdin: [Getter],
//      openStdin: [Function],
//      exit: [Function],
//      kill: [Function],
//      _immediateCallback: [Function: processImmediate],
//      argv0: 'node',
//      mainModule: 
//       Module {
//         id: '.',
//         exports: {},
//         parent: null,
//         filename: '/Users/a408113/Development/JS/js_study/isTrustedTest.js',
//         loaded: false,
//         children: [],
//         paths: [Array] } },
//   Buffer: 
//    { [Function: Buffer]
//      poolSize: 8192,
//      from: [Function],
//      alloc: [Function],
//      allocUnsafe: [Function],
//      allocUnsafeSlow: [Function],
//      isBuffer: [Function: isBuffer],
//      compare: [Function: compare],
//      isEncoding: [Function],
//      concat: [Function],
//      byteLength: [Function: byteLength],
//      [Symbol(node.isEncoding)]: [Function] },
//   clearImmediate: [Function],
//   clearInterval: [Function],
//   clearTimeout: [Function],
//   setImmediate: { [Function: setImmediate] [Symbol(util.promisify.custom)]: [Function] },
//   setInterval: [Function],
//   setTimeout: { [Function: setTimeout] [Symbol(util.promisify.custom)]: [Function] } }